name: "Build"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
    if: (github.event_name == 'pull_request' || github.event_name == 'push') && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    name: Build 
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore -o br-${{ matrix.os }}

    - name: Test
      working-directory: ./src
      run: dotnet test

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: br-${{ matrix.os }}.zip
        path: ./src/br-${{ matrix.os }}

    - name: ZIP Release (Ubuntu)
      working-directory: ./src
      if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/')
      run: sudo apt-get install zip | zip -r br-${{ matrix.os }}.zip br-${{ matrix.os }}

    - name: ZIP Release (macOS)
      working-directory: ./src
      if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
      run: zip -r br-${{ matrix.os }}.zip br-${{ matrix.os }}

    - name: ZIP Release (Windows)
      working-directory: ./src
      if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/')
      run: Compress-Archive -Path br-${{ matrix.os }} -DestinationPath br-${{ matrix.os }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./src/br-${{ matrix.os }}.zip
